export const fitoStyleOptions = {
    hideSendBox: false,
    hideUploadButton: true,
    sendBoxBackground: '#F3F4F6',
    sendBoxHeight: 100,
    sendBoxMaxHeight: 200,
    sendBoxTextColor: 'Black',
    sendBoxBorderBottom: 'solid 2px #009FDB',
    sendBoxBorderLeft: 'solid 2px #009FDB',
    sendBoxBorderRight: 'solid 2px #009FDB',
    sendBoxBorderTop: 'solid 2px #009FDB',
    bubbleBackground: '#009FDB',
    bubbleBorderColor: '#E6E6E6',
    bubbleBorderRadius: 12,
    bubbleBorderStyle: 'solid',
    bubbleBorderWidth: 1,
    bubbleFromUserBackground: '#BDC2C7',
    bubbleFromUserBorderColor: '#E6E6E6',
    bubbleFromUserBorderRadius: 12,
    bubbleFromUserBorderStyle: 'solid',
    bubbleFromUserBorderWidth: 1,
    bubbleFromUserNubOffset: 'bottom',
    bubbleFromUserNubSize: 0,
    bubbleFromUserTextColor: 'Black',
    bubbleImageHeight: 240,
    bubbleMaxWidth: 480,
    bubbleMinHeight: 40,
    bubbleMinWidth: 250,
    bubbleNubOffset: 'bottom',
    bubbleNubSize: 5,
    bubbleTextColor: 'white',
    avatarSize: 50
  };